services:

  db:
    image: postgres:15
    container_name: student_db
    restart: always
    environment:
      POSTGRES_DB: students_db
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    volumes:
      - db_data:/var/lib/postgresql/data
      - ./services/db/init.sql:/docker-entrypoint-initdb.d/init.sql

  api:
    build: ./services/api
    container_name: student_api
    restart: always
    depends_on:
      - db
    environment:
      DATABASE_URL: postgresql://admin:admin@db:5432/students_db
    ports:
      - "3000:3000"

  frontend:
    build: ./services/frontend
    container_name: student_frontend
    restart: always
    depends_on:
      - api
    ports:
      - "80:80"

volumes:
  db_data:
